### ISSUE TITLE
Tokens never expire

### ISSUE THREAD

**Issue by Earlo** [futurice/wappuapp-backend#52]
Currently tokens front end has are eternally valid. So, for example it's possible to copy one post request for drinking sima and keep sending that over and over for automated sima drinking. 

Is this intended?

**Comment by kaupunki-apina** [comment]
Behavior is an known side effect of having a minimal barrier of entry, as the client is never strongly authenticated beyond having the correct API key. This was an UX rather than security driven decision.

We are aware of the ongoing automation of certain tasks.
